name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Java code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Checkstyle
        run: |
          sudo apt update
          sudo apt install -y checkstyle
          curl -LJO https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

      - name: Run Checkstyle
        run: |
          checkstyle -c google_checks.xml $(find . -name "*.java")

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and run tests
        run: |
          javac -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar $(find . -name "*.java")
          java -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:. org.junit.runner.JUnitCore lab.tests.AppTest

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t lab0_log430 .

  push-to-dockerhub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "mdyoucef00" --password-stdin

      - name: Build and tag image
        run: |
          docker build -t docker.io/mdyoucef00/lab0_log430:latest .

      - name: Push image
        run: |
          docker push docker.io/mdyoucef00/lab0_log430:latest